### ISSUE TITLE
关于kmeans 初始化

### ISSUE THREAD

**Issue by Yonoi** [HonghuiBao2000/LETTER#2]
大佬，请教一下，这里的kmeans初始化密码本，是利用第一个batch size初始化吗？那这样怎么保证第一个batch size的样本能代表全部呢？期待你的回复。

**Comment by HonghuiBao2000** [comment]
你好，感谢你对我们工作的关注。

在LETTER中，我们是利用数据集里**所有的item embedding**，进行初始化，你可以参考我们trainer.py文件的vq_init方法。

**Comment by Yonoi** [comment]
感谢～
