### ISSUE TITLE
关于CF_Embedding的问题

### ISSUE THREAD

**Issue by Maribel-Hearn** [HonghuiBao2000/LETTER#5]
你好，我尝试运行了代码里的Instruments数据集，但是想要运行其他数据集似乎需要与Instruments类似的Instruments_sasrecs.pth文件，再经过CF_ckpt_process处理之后得到dataset-sasrecs-32d.pt，才能继续运行，想请教一下应该怎么获得类似dataset_sasrecs.pth的文件呢？有源码可以进行参考吗？

**Comment by HonghuiBao2000** [comment]
Hiiii 感谢对我们工作的关注。是的，你需要使用well-trained的CF Model (e.g. SASRec) 的item embedding。关于SASRec的代码，可以参照 [SASRec](https://github.com/pmixer/SASRec.pytorch)，希望对你有帮助 ：）

**Comment by HonghuiBao2000** [comment]
@Maribel-Hearn

**Comment by Maribel-Hearn** [comment]
非常感谢！我到时候会去参考一下相关的代码工作的
