### ISSUE TITLE
文件缺失

### ISSUE THREAD

**Issue by xiaofanbufanla** [HonghuiBao2000/LETTER#6]
您好老师冒昧打扰一下，我在尝试复现数据集时找不到data_path ../data/Instruments/Instruments.emb-llama-td.npy这个文件夹，怎么解决呢？

**Comment by HonghuiBao2000** [comment]
@xiaofanbufanla  你好，感谢对我们的工作的关注。这个文件可以通过 ‘data_process’的[amazon_text_emb.py](https://github.com/HonghuiBao2000/LETTER/blob/master/data_process/amazon_text_emb.py)进行生成 ：）

**Comment by xiaofanbufanla** [comment]
> 你好，感谢对我们的工作的关注。这个文件可以通过 'data_process'的[amazon_text_emb.py](https://github.com/HonghuiBao2000/LETTER/blob/master/data_process/amazon_text_emb.py)进行生成 :)

谢谢您的回复，那我先运行完这个[amazon_text_emb.py]，再按照您readme的步骤进行复现嘛

**Comment by HonghuiBao2000** [comment]
@xiaofanbufanla  是的，之后就可以训练tokenizer了。

**Comment by xiaofanbufanla** [comment]
> @xiaofanbufanla 是的，之后就可以训练tokenizer了。

哇太感谢啦，谢谢您的回复，开心！
