### ISSUE TITLE
参数配置

### ISSUE THREAD

**Issue by xiaofanbufanla** [HonghuiBao2000/LETTER#7]
不好意思打扰一下老师，我还有一个问题，运行data_process/amazon_text_emb.py文件时，您给的代码里没有设置parser.add_argument('--plm_checkpoint', type=str, default='')这个参数，我应该怎么设置呢，求解答。

**Comment by HonghuiBao2000** [comment]
@xiaofanbufanla 这个部分是在对item进行semantic的encoding - 你可以选择适当的模型完成这一步，当然如果想要复现我们的效果，推荐使用LLaMA1-7B
