### ISSUE TITLE
error arised during the training process of 'LETTER-TIGER'

### ISSUE THREAD

**Issue by chenzhouli** [HonghuiBao2000/LETTER#8]
I run the command "bash run_train.sh"on Instruments dataset in LETTER-TIGER.
While training around 60%/50%, an error arised:
"There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight', 'lm_head.weight']."
tried many ways, still no clue.

**Comment by HonghuiBao2000** [comment]
@chenzhouli Hiiii! Thanks for your interest in our work. Unfortunately, I haven't encountered this issue before. Here are my suggestions:

1. Please provide a more detailed description of the issue, including where it occurred.
2. Check if you've made any changes, as the code has been verified by multiple peers.

Based on the information you've shared, it seems likely that your training has converged. Feel free to reach out if you have any further questions! : )

**Comment by chenzhouli** [comment]
I found that the warning, "There were missing keys in the checkpoint model loaded," appeared in the _load_best_model function when load_best_model_at_end=True, indicating that my training did converge. 

This issue may be related to the Transformers version I am using: the warning appeared with 4.46.1, while in 4.27.0, training proceeded without issues, and the pytorch_model.bin file was saved successfully.

Thanks for your suggestion!

**Comment by HonghuiBao2000** [comment]
@chenzhouli  Nice! Glad to hear that!

**Comment by bystander563** [comment]
我也遇到了这个问题，而且将transformer版本换成4.27.0警告依然存在。不过模型也可以成功收敛，不知道这个警告有没有其他影响
